[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
script = "script"

# Solidity version
solc_version = "0.8.26"

# Enable IR-based code generation (required for FHE)
via_ir = true

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Verbose output
verbosity = 2

# Gas reporting
gas_reports = ["*"]

# Coverage
fuzz_runs = 1000
fuzz_max_local_rejects = 10000
fuzz_max_global_rejects = 10000

# Etherscan API keys (add your own)
etherscan_api_key = "${ETHERSCAN_API_KEY}"

# RPC URLs (add your own)
# rpc_endpoints = {
#     mainnet = "${MAINNET_RPC_URL}",
#     sepolia = "${SEPOLIA_RPC_URL}",
#     anvil = "http://localhost:8545"
# }

# Fork settings
# fork_url = "${MAINNET_RPC_URL}"
# fork_block_number = 20000000

# Test settings
fuzz = true
invariant = true
invariant_runs = 1000
invariant_depth = 15

# Deployment settings
# broadcast = true
# verify = true
# slow = true

# FHE specific settings
extra_output = ["storageLayout", "metadata"]
extra_output_files = ["metadata"]
